### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-closing#203]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_cutoff_base - By @dzungtran89 - #213
- [ ] account_cutoff_picking (ex account_cutoff_accrual_picking) - By @alexis-via - https://github.com/OCA/account-closing/pull/230
- [ ] account_cutoff_accrual_subscription
- [x] account_cutoff_base - By @dzungtran89 - https://github.com/OCA/account-closing/pull/213
- [x] account_cutoff_start_end_dates - By @dzungtran89 - https://github.com/OCA/account-closing/pull/216
- [ ] account_invoice_start_end_dates - By @FrancoMaxime - #206
- [ ] account_multicurrency_revaluation

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by dzungtran89** [comment]
- `account_cutoff_base`: https://github.com/OCA/account-closing/pull/213

**Comment by dzungtran89** [comment]
- `account_cutoff_accrual_picking`: https://github.com/OCA/account-closing/pull/215

**Comment by dzungtran89** [comment]
- `account_cutoff_start_end_dates`: https://github.com/OCA/account-closing/pull/216

**Comment by alexis-via** [comment]
I plan to migrate the module account_cutoff_accrual_picking from this v14 PR https://github.com/OCA/account-closing/pull/225 and rename the module to account_cutoff_picking (with this PR, it now supports both accruals and prepaid, so we need to remove "accrual" in the module name).

**Comment by alexis-via** [comment]
I have another idea for v16 for account_cutoff_base: 
- remove the 2 fields account_accrued_revenue_id and account_accrued_expense_id from account.tax
- replace it by 2 fields on res.company: accrued_revenue_tax_account_id and accrued_expense_tax_account_id

Reminder: these fields are only useful if you set accrual_taxes=true on res.company (should be set to True for France for instance). As using tax in accrual moves is a pretty useless thing (but in France, we like useless things !), I don't imagine someone needing different accounts for different VAT rates.
Advantage of this change: save time on configuration. Avoid addition of the 2 current fields on account.tax.template.

@fclementic2c any objection ?

**Comment by fclementic2c** [comment]
@alexis-via more simple but less rational ... In the standard, for example, Odoo put the cash basis information on the tax so I would not change.
But if you change this it is ok I can live with this.

**Comment by Borruso** [comment]
Migration `account_fiscal_year_closing` #248

**Comment by SilvioC2C** [comment]
Migrating `account_invoice_start_end_dates_move` in https://github.com/OCA/account-closing/pull/292
