### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-closing#30]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] account_cutoff_base https://github.com/OCA/account-closing/pull/37 by @alexis-via 
- [ ] account_cutoff_accrual_base - By @grindtildeath - #42 
- [ ] account_cutoff_accrual_picking
- [x] account_cutoff_prepaid https://github.com/OCA/account-closing/pull/37 by @alexis-via 
- [ ] account_invoice_accrual WIP by @adrienpeiffer 
- [ ] account_multicurrency_revaluation_report
- [ ] account_multicurrency_revaluation - By @grindtildeath  - #46

**Comment by blaggacao** [comment]
@pedrobaeza Do you know of someone, that might have got a schematic idea about how a refactoring of account_multicurrency_revaluation would look like?
I mean, the problem, I have, is to understand and trace conceptual changes while being short of referable knowledge, either in v9 or in v8 in the multicurrency field.

**Comment by rvalyi** [comment]
@blaggacao I may miss some people but I would advice you get in touch with @alexis-via (Akretion) and @fclementic2c (CampToCamp). Good luck. Nice to see your willingness to work inside the OCA.

**Comment by blaggacao** [comment]
:+1: that's a nice welcome, thanks. :)

**Comment by alexis-via** [comment]
FYI, I plan to push my port of account_cutoff_prepaid to v9 and the underlying modules this WE.
