### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-closing#40]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_cutoff_accrual_base - By @Cedric-Pigeon - #43
- [ ] account_cutoff_accrual_picking
- [x] account_cutoff_base - By @adrienpeiffer - #41 
- [x] account_cutoff_prepaid - By @adrienpeiffer - #41 
- [x] account_fiscal_year_closing - By @jbeficent - #57 
- [x] account_invoice_accrual - By @Cedric-Pigeon - #45 
- [x] account_invoice_start_end_dates - By @adrienpeiffer - #41 
- [ ] account_multicurrency_revaluation - By @grindtildeath - #47 
- [ ] account_multicurrency_revaluation_report By @yvaucher - #48
