### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-closing#55]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_cutoff_accrual_base - By @oleksandrpaziuk - #62 
- [ ] account_cutoff_accrual_picking
- [x] account_cutoff_base - By @oleksandrpaziuk - #61 
- [x] account_cutoff_prepaid - By @oleksandrpaziuk - #60 
- [x] ~~account_fiscal_year_closing - By @jbeficent - #58~~ No need of making the "account FY closing"
- [x] account_invoice_start_end_dates - By @oleksandrpaziuk - #63 
- [x] account_multicurrency_revaluation - By @oleksandrpaziuk - #64 
- [ ] account_multicurrency_revaluation_report

**Comment by emagdalenaC2i** [comment]
@pedrobaeza 
account_cutoff_accrual_base - By @oleksandrpaziuk - #62 is done
account_multicurrency_revaluation - By @oleksandrpaziuk - #64 is done

**Comment by FrancescaBianchini** [comment]
@pedrobaeza I'm using odoo v.11 and I was looking for module account_fiscal_year_closing.
You wrote that it is no more necessary to migrate this module, can you tell me why?
Is there an alternative way to close year without this module?
Thanks in advance

**Comment by pedrobaeza** [comment]
From v9, there's no need of closing entries, as data is computed on the fly. The module was initially implemented/migrated due to the lack of knowledge of doing the "Odoo" way, but preserving that way only provokes to have to adjust the logic in all places, so better to get used to new way.

**Comment by UnixedIT** [comment]
Could you advise where is the document to learn how to close the fiscal year in the new way. for Odoo v11 CE.
